/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repuestos;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author iFreuk
 */
public class AsociarPartesAuto extends javax.swing.JFrame {

    /**
     * Creates new form InsertarParte
     */
    JFrame principal;
    
    public WindowListener c = new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent e) {
            cerrar(principal);
        }
    };
    
    public AsociarPartesAuto(JFrame p) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.addWindowListener(c);
        cargarPartes();
        this.setVisible(true);
        principal = p;
    }
    
    void cerrar(JFrame p){
        p.setVisible(true);
        this.dispose();
    }
    
    void cargarPartes(){
        try{
            Repuestos.getPartes(ComboPartes);
            
        }catch(SQLException ex){
            Logger.getLogger(AsociarOrden.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ComboPartes = new javax.swing.JComboBox<>();
        AsoPartAuto = new javax.swing.JLabel();
        AsoAutoPart = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        TITULOASOCIAR = new javax.swing.JLabel();
        ComboAutos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Asociar Parte y Auto");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(373, 237));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ComboPartes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(ComboPartes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 180, -1));

        AsoPartAuto.setBackground(new java.awt.Color(204, 204, 204));
        AsoPartAuto.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        AsoPartAuto.setForeground(new java.awt.Color(255, 255, 255));
        AsoPartAuto.setText("Parte:");
        jPanel1.add(AsoPartAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        AsoAutoPart.setBackground(new java.awt.Color(204, 204, 204));
        AsoAutoPart.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        AsoAutoPart.setForeground(new java.awt.Color(255, 255, 255));
        AsoAutoPart.setText("Auto:");
        jPanel1.add(AsoAutoPart, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setText("Asociar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        TITULOASOCIAR.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TITULOASOCIAR.setForeground(new java.awt.Color(255, 255, 255));
        TITULOASOCIAR.setText("Asociar Parte");
        jPanel1.add(TITULOASOCIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        ComboAutos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ComboAutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Camry", "Corolla", "CX-5", "Eclipse", "F18", "Fox", "Golf", "Lancer", "Mazda", "Murano", "Pajero", "Prius", "Sentra", "Terrano", "Titan", "X6 M", "X-Trail", "Yaris" }));
        ComboAutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboAutosActionPerformed(evt);
            }
        });
        jPanel1.add(ComboAutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            boolean a = Repuestos.CreaAso(ComboPartes.getSelectedItem().toString(), ComboAutos.getSelectedItem().toString());
            if(a)
                JOptionPane.showMessageDialog(this, "Asociasion creada", "Info", 1);
            else
                JOptionPane.showMessageDialog(this, "Algo salió mal", "Advertencia", 2);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Parte ya asociada", "Advertencia", 2);
            //Logger.getLogger(AsociarPartesAuto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ComboAutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboAutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboAutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsociarPartesAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsociarPartesAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsociarPartesAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsociarPartesAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsociarPartesAuto(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AsoAutoPart;
    private javax.swing.JLabel AsoPartAuto;
    private javax.swing.JComboBox<String> ComboAutos;
    private javax.swing.JComboBox<String> ComboPartes;
    private javax.swing.JLabel TITULOASOCIAR;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
