/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repuestos;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author iFreuk
 */
public class AsociarPartesProvedor extends javax.swing.JFrame {

    /**
     * Creates new form InsertarParte
     */
    JFrame principal;
    
    public WindowListener c = new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent e) {
            cerrar(principal);
        }
    };
    
    public AsociarPartesProvedor(JFrame p) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.addWindowListener(c);
        cargarPartes();
        this.setVisible(true);
        principal = p;
    }
    
    void cerrar(JFrame p){
        p.setVisible(true);
        this.dispose();
    }
    
    void cargarPartes(){
        try{
            Repuestos.getPartes(ComboPartes);
            
        }catch(SQLException ex){
            Logger.getLogger(AsociarOrden.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ParteAsoLabel = new javax.swing.JLabel();
        ProveedorAsoLabel = new javax.swing.JLabel();
        ComboAsoProv = new javax.swing.JComboBox<>();
        AsociarButton = new javax.swing.JButton();
        TITULOINSERTARp = new javax.swing.JLabel();
        ComboPartes = new javax.swing.JComboBox<>();
        PorcentajeField = new javax.swing.JFormattedTextField(new Integer(3));
        CostoLabel = new javax.swing.JLabel();
        PorcentajeLabel1 = new javax.swing.JLabel();
        PorcentajeSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Asociar Parte y Provedor");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ParteAsoLabel.setBackground(new java.awt.Color(204, 204, 204));
        ParteAsoLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ParteAsoLabel.setForeground(new java.awt.Color(255, 255, 255));
        ParteAsoLabel.setText("Parte");
        jPanel1.add(ParteAsoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        ProveedorAsoLabel.setBackground(new java.awt.Color(204, 204, 204));
        ProveedorAsoLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ProveedorAsoLabel.setForeground(new java.awt.Color(255, 255, 255));
        ProveedorAsoLabel.setText("Proveedor");
        jPanel1.add(ProveedorAsoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        ComboAsoProv.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ComboAsoProv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auto Repuestos Jiménez", "Autopartes Mandi", "Autopartes USA", "J y A Autopartes", "LACOR Repuestos", "Megapartes Martínez", "Repuestos ABZ", "Repuestos Zúñiga", "Servicios Omega", "Super Repuestos" }));
        jPanel1.add(ComboAsoProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        AsociarButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        AsociarButton.setText("Asociar ✅");
        AsociarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsociarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AsociarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 170, 90));

        TITULOINSERTARp.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TITULOINSERTARp.setForeground(new java.awt.Color(255, 255, 255));
        TITULOINSERTARp.setText("Asociar Parte Proveedor");
        jPanel1.add(TITULOINSERTARp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        ComboPartes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(ComboPartes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 180, -1));

        PorcentajeField.setText("0");
        PorcentajeField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PorcentajeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorcentajeFieldActionPerformed(evt);
            }
        });
        PorcentajeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PorcentajeFieldKeyPressed(evt);
            }
        });
        jPanel1.add(PorcentajeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 134, -1));

        CostoLabel.setBackground(new java.awt.Color(204, 204, 204));
        CostoLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CostoLabel.setForeground(new java.awt.Color(255, 255, 255));
        CostoLabel.setText("Costo en Colones");
        jPanel1.add(CostoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        PorcentajeLabel1.setBackground(new java.awt.Color(204, 204, 204));
        PorcentajeLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PorcentajeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        PorcentajeLabel1.setText("Porcentaje Beneficio");
        jPanel1.add(PorcentajeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        PorcentajeSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PorcentajeSpinnerStateChanged(evt);
            }
        });
        jPanel1.add(PorcentajeSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 57, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AsociarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsociarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AsociarButtonActionPerformed

    private void PorcentajeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorcentajeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PorcentajeFieldActionPerformed

    private void PorcentajeFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PorcentajeFieldKeyPressed
        //CostoFinal.setText(calcValor());
    }//GEN-LAST:event_PorcentajeFieldKeyPressed

    private void PorcentajeSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PorcentajeSpinnerStateChanged
        //CostoFinal.setText(calcValor());
    }//GEN-LAST:event_PorcentajeSpinnerStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsociarPartesProvedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsociarPartesProvedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsociarPartesProvedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsociarPartesProvedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsociarPartesProvedor(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AsociarButton;
    private javax.swing.JComboBox<String> ComboAsoProv;
    private javax.swing.JComboBox<String> ComboPartes;
    private javax.swing.JLabel CostoLabel;
    private javax.swing.JLabel ParteAsoLabel;
    private javax.swing.JFormattedTextField PorcentajeField;
    private javax.swing.JLabel PorcentajeLabel1;
    private javax.swing.JSpinner PorcentajeSpinner;
    private javax.swing.JLabel ProveedorAsoLabel;
    private javax.swing.JLabel TITULOINSERTARp;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
