/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repuestos;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class CrearOrden extends javax.swing.JFrame {

    /**
     * Creates new form CrearOrden
     */
    JFrame principal;
    
    public WindowListener c = new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent e) {
            cerrar(principal);
        }
    };
    
    public CrearOrden(JFrame p) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.addWindowListener(c);
        this.setVisible(true);
        principal = p;
        Panel3.setVisible(false);
        
        TextDia.addKeyListener(new KeyListener(){
        @Override
        public void keyTyped(KeyEvent e)

        {if (TextDia.getText().length()== 1){
             TextMes.requestFocus();
        }if (TextDia.getText().length()== 2)
            e.consume();
        }
        @Override
        public void keyPressed(KeyEvent arg0) {
        }
        @Override
        public void keyReleased(KeyEvent arg0) {
        }
        });
        
        TextMes.addKeyListener(new KeyListener(){
        @Override
        public void keyTyped(KeyEvent e)

        {if (TextMes.getText().length()== 1){
             TextAnno.requestFocus();
        }if (TextMes.getText().length()== 2)
            e.consume();
        }
        @Override
        public void keyPressed(KeyEvent arg0) {
        }
        @Override
        public void keyReleased(KeyEvent arg0) {
        }
        });
        
        TextAnno.addKeyListener(new KeyListener(){
        @Override
        public void keyTyped(KeyEvent e)

        {if (TextAnno.getText().length()== 4)
             e.consume();
        }
        @Override
        public void keyPressed(KeyEvent arg0) {
        }
        @Override
        public void keyReleased(KeyEvent arg0) {
        }
        });
    }
    
    void cerrar(JFrame p){
        p.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Panel2 = new javax.swing.JPanel();
        LabelCedulaCliente = new javax.swing.JLabel();
        TextCedulaPersona = new javax.swing.JTextField();
        Panel3 = new javax.swing.JPanel();
        LabelCedulaOrg = new javax.swing.JLabel();
        TextCedulaOrg = new javax.swing.JTextField();
        Panel1 = new javax.swing.JPanel();
        LabelFecha2 = new javax.swing.JLabel();
        LabelFecha1 = new javax.swing.JLabel();
        LabelFecha = new javax.swing.JLabel();
        Label = new javax.swing.JLabel();
        RadioPersona = new javax.swing.JRadioButton();
        RadioOrg = new javax.swing.JRadioButton();
        TextAnno = new javax.swing.JTextField();
        TextDia = new javax.swing.JTextField();
        TextMes = new javax.swing.JTextField();
        BotonCrearOrden = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Crear Orden");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel2.setBackground(new java.awt.Color(51, 51, 51));
        Panel2.setPreferredSize(new java.awt.Dimension(500, 650));
        Panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelCedulaCliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LabelCedulaCliente.setForeground(new java.awt.Color(204, 204, 204));
        LabelCedulaCliente.setText("Cédula:");
        Panel2.add(LabelCedulaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        TextCedulaPersona.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Panel2.add(TextCedulaPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 360, -1));

        getContentPane().add(Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, 80));

        Panel3.setBackground(new java.awt.Color(51, 51, 51));
        Panel3.setPreferredSize(new java.awt.Dimension(500, 520));
        Panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelCedulaOrg.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        LabelCedulaOrg.setForeground(new java.awt.Color(204, 204, 204));
        LabelCedulaOrg.setText("Cédula Jurídica:");
        Panel3.add(LabelCedulaOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        TextCedulaOrg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Panel3.add(TextCedulaOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 330, -1));

        getContentPane().add(Panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, 80));

        Panel1.setBackground(new java.awt.Color(51, 51, 51));
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelFecha2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LabelFecha2.setForeground(new java.awt.Color(204, 204, 204));
        LabelFecha2.setText("/");
        Panel1.add(LabelFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 20, -1));

        LabelFecha1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LabelFecha1.setForeground(new java.awt.Color(204, 204, 204));
        LabelFecha1.setText("/");
        Panel1.add(LabelFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 20, -1));

        LabelFecha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LabelFecha.setForeground(new java.awt.Color(204, 204, 204));
        LabelFecha.setText("Fecha:");
        Panel1.add(LabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        Label.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Label.setForeground(new java.awt.Color(204, 204, 204));
        Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label.setText("Crear Orden");
        Panel1.add(Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 500, -1));

        RadioPersona.setBackground(new java.awt.Color(55, 55, 55));
        buttonGroup1.add(RadioPersona);
        RadioPersona.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        RadioPersona.setForeground(new java.awt.Color(204, 204, 204));
        RadioPersona.setSelected(true);
        RadioPersona.setText("Persona");
        RadioPersona.setFocusPainted(false);
        RadioPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioPersonaActionPerformed(evt);
            }
        });
        Panel1.add(RadioPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        RadioOrg.setBackground(new java.awt.Color(55, 55, 55));
        buttonGroup1.add(RadioOrg);
        RadioOrg.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        RadioOrg.setForeground(new java.awt.Color(204, 204, 204));
        RadioOrg.setText("Organización");
        RadioOrg.setFocusPainted(false);
        RadioOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioOrgActionPerformed(evt);
            }
        });
        Panel1.add(RadioOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        TextAnno.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        TextAnno.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Panel1.add(TextAnno, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 60, -1));

        TextDia.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        TextDia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Panel1.add(TextDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 40, -1));

        TextMes.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        TextMes.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Panel1.add(TextMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 40, -1));

        BotonCrearOrden.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        BotonCrearOrden.setText("Crear");
        BotonCrearOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearOrdenActionPerformed(evt);
            }
        });
        Panel1.add(BotonCrearOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        getContentPane().add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioPersonaActionPerformed
        Panel2.setVisible(true);
        Panel3.setVisible(false);
    }//GEN-LAST:event_RadioPersonaActionPerformed

    private void RadioOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioOrgActionPerformed
        Panel2.setVisible(false);
        Panel3.setVisible(true);
    }//GEN-LAST:event_RadioOrgActionPerformed

    boolean verificarFechas(String dia, String mes, String anno){
        if(dia.isEmpty() || mes.isEmpty() || anno.isEmpty()){
            JOptionPane.showMessageDialog(this, "Los campos para la fecha no pueden ser vacíos", "Advertencia", 2);
            return false;
        }else if(!(Repuestos.isNumeric(dia) || Repuestos.isNumeric(mes) || Repuestos.isNumeric(anno))){
            JOptionPane.showMessageDialog(this, "Los campos para la fecha deben ser números enteros", "Advertencia", 2);
            return false;
        }else if(Integer.parseInt(dia) > 31){
            JOptionPane.showMessageDialog(this, "Los días van de 1 a 31", "Advertencia", 2);
            return false;
        }else if(Integer.parseInt(mes) > 12){
            JOptionPane.showMessageDialog(this, "Los meses van de 1 a 12", "Advertencia", 2);
            return false;
        }else if(Integer.parseInt(anno) > 2020 || Integer.parseInt(anno) < 1900){
            JOptionPane.showMessageDialog(this, "El año debe ser de 1900 a 2020", "Advertencia", 2);
            return false;
        }
        return true;
    }
    
    private void BotonCrearOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearOrdenActionPerformed
        try {
            int cedula;
            String tipo, dia, mes, anno;
            dia = TextDia.getText();
            mes = TextMes.getText();
            anno = TextAnno.getText();
            
            if(!verificarFechas(dia, mes, anno))
                return;
            
            String fecha = anno + "-" + mes + "-" + dia;
            Date sqlFecha = Date.valueOf(fecha);
            
            if(RadioPersona.isSelected()){
                tipo = "Persona";
                if(TextCedulaPersona.getText().trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "El campo de cedula no puede ser vacío", "Advertencia", 2);
                    return;
                }else if(TextCedulaPersona.getText().trim().length() < 9){
                    JOptionPane.showMessageDialog(this, "Cédula inválida (menor a 9 dígitos)", "Advertencia", 2);
                    return;
                }
                cedula = Integer.parseInt(TextCedulaPersona.getText());
                
            }else{
                tipo = "Organizacion";
                if(TextCedulaOrg.getText().trim().isEmpty()){
                    JOptionPane.showMessageDialog(this, "El campo de cedula jurídica no puede ser vacío", "Advertencia", 2);
                    return;
                }else if(TextCedulaOrg.getText().trim().length() < 9){
                    JOptionPane.showMessageDialog(this, "Cédula jurídica inválida (menor a 9 dígitos)", "Advertencia", 2);
                    return;
                }
                cedula = Integer.parseInt(TextCedulaOrg.getText());
            }
            
            
            boolean a = Repuestos.crearOrden(cedula, tipo, sqlFecha, this);
            if(a){
                JOptionPane.showMessageDialog(this, "Orden creada", "Info", 1);
                siguientePaso(cedula, tipo, sqlFecha);
            }
            
                
            
        } catch (SQLException ex) {
            Logger.getLogger(CrearOrden.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Error, cédula debe ser un número entero", "Advertencia", 2);
        }
    }//GEN-LAST:event_BotonCrearOrdenActionPerformed

    void siguientePaso(int cedula, String tipo, Date fecha){
        this.dispose();
        new AsociarOrden(principal, cedula, tipo, fecha);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearOrden(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCrearOrden;
    private javax.swing.JLabel Label;
    private javax.swing.JLabel LabelCedulaCliente;
    private javax.swing.JLabel LabelCedulaOrg;
    private javax.swing.JLabel LabelFecha;
    private javax.swing.JLabel LabelFecha1;
    private javax.swing.JLabel LabelFecha2;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JRadioButton RadioOrg;
    private javax.swing.JRadioButton RadioPersona;
    private javax.swing.JTextField TextAnno;
    private javax.swing.JTextField TextCedulaOrg;
    private javax.swing.JTextField TextCedulaPersona;
    private javax.swing.JTextField TextDia;
    private javax.swing.JTextField TextMes;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
