/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repuestos;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author iFreuk
 */
public class InsertarParte extends javax.swing.JFrame {

    /**
     * Creates new form InsertarParte
     */
    JFrame principal;
    
    
    public WindowListener c = new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent e) {
            cerrar(principal);
        }
    };
    
    public InsertarParte(JFrame p) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.addWindowListener(c);
        this.setVisible(true);
        principal = p;
    }
    
    void cerrar(JFrame p){
        p.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panelinsertar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        FabricanteLabel = new javax.swing.JLabel();
        MarcaLabel = new javax.swing.JLabel();
        NombreField = new javax.swing.JTextField();
        NombreLabel = new javax.swing.JLabel();
        InsertarParte = new javax.swing.JButton();
        MarcaCombo = new javax.swing.JComboBox<>();
        FabCombo = new javax.swing.JComboBox<>();
        TITULOINSERTARp = new javax.swing.JLabel();
        TITULOASOCIAR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Insertar Parte");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panelinsertar.setBackground(new java.awt.Color(51, 51, 51));
        Panelinsertar.setForeground(new java.awt.Color(51, 51, 51));
        Panelinsertar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Panelinsertar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 73, -1, -1));

        FabricanteLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        FabricanteLabel.setForeground(new java.awt.Color(255, 255, 255));
        FabricanteLabel.setText("Fabricante");
        Panelinsertar.add(FabricanteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        MarcaLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        MarcaLabel.setForeground(new java.awt.Color(255, 255, 255));
        MarcaLabel.setText("Marca");
        Panelinsertar.add(MarcaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        NombreField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Panelinsertar.add(NombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 230, -1));

        NombreLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        NombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        NombreLabel.setText("Nombre");
        Panelinsertar.add(NombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        InsertarParte.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        InsertarParte.setText("🆗");
        InsertarParte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarParteActionPerformed(evt);
            }
        });
        Panelinsertar.add(InsertarParte, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        MarcaCombo.setForeground(new java.awt.Color(0, 0, 0));
        MarcaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delphi", "Falken", "Kelly", "Bondo", "Goyo", "Koni", "Kleber", "Fuller", "Armstrong", "Walker" }));
        Panelinsertar.add(MarcaCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 120, 40));

        FabCombo.setForeground(new java.awt.Color(0, 0, 0));
        FabCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "International Spare Parts", "Auto Spare Parts", "AJS Auto Parts", "Discounted Parts" }));
        Panelinsertar.add(FabCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 200, 40));

        TITULOINSERTARp.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TITULOINSERTARp.setForeground(new java.awt.Color(255, 255, 255));
        TITULOINSERTARp.setText("Insertar Parte");
        Panelinsertar.add(TITULOINSERTARp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        getContentPane().add(Panelinsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 372));

        TITULOASOCIAR.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TITULOASOCIAR.setForeground(new java.awt.Color(255, 255, 255));
        TITULOASOCIAR.setText("Asociar Parte");
        getContentPane().add(TITULOASOCIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertarParteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarParteActionPerformed
        int fabricante = FabCombo.getSelectedIndex()+1;
        int marca = MarcaCombo.getSelectedIndex()+1;
        String nombre = NombreField.getText();
        try{
        boolean Insertado = Repuestos.InsertPartes(fabricante, nombre, marca);
        if(Insertado){
            JOptionPane.showMessageDialog(this, "Insertado con exito", "Info", 1);
            }
        }
        catch(SQLException e){
            Logger.getLogger(InsertarParte.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_InsertarParteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarParte(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> FabCombo;
    private javax.swing.JLabel FabricanteLabel;
    private javax.swing.JButton InsertarParte;
    private javax.swing.JComboBox<String> MarcaCombo;
    private javax.swing.JLabel MarcaLabel;
    private javax.swing.JTextField NombreField;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JPanel Panelinsertar;
    private javax.swing.JLabel TITULOASOCIAR;
    private javax.swing.JLabel TITULOINSERTARp;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
