/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repuestos;

/**
 *
 * @author iFreuk
 */
public class InsertarParte extends javax.swing.JFrame {

    /**
     * Creates new form InsertarParte
     */
    public InsertarParte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panelinsertar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        FabricanteCombo = new javax.swing.JComboBox();
        FabricanteLabel = new javax.swing.JLabel();
        MarcaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panelinsertar.setForeground(new java.awt.Color(51, 51, 51));

        FabricanteCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        FabricanteLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        FabricanteLabel.setText("Fabricante");

        MarcaLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        MarcaLabel.setText("Marca");

        javax.swing.GroupLayout PanelinsertarLayout = new javax.swing.GroupLayout(Panelinsertar);
        Panelinsertar.setLayout(PanelinsertarLayout);
        PanelinsertarLayout.setHorizontalGroup(
            PanelinsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelinsertarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(163, 163, 163))
            .addGroup(PanelinsertarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelinsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MarcaLabel)
                    .addGroup(PanelinsertarLayout.createSequentialGroup()
                        .addComponent(FabricanteLabel)
                        .addGap(18, 18, 18)
                        .addComponent(FabricanteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(585, Short.MAX_VALUE))
        );
        PanelinsertarLayout.setVerticalGroup(
            PanelinsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelinsertarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(PanelinsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FabricanteLabel)
                    .addComponent(FabricanteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(MarcaLabel)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        getContentPane().add(Panelinsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 372));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarParte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox FabricanteCombo;
    private javax.swing.JLabel FabricanteLabel;
    private javax.swing.JLabel MarcaLabel;
    private javax.swing.JPanel Panelinsertar;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
