/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repuestos;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JFrame;

/**
 *
 * @author iFreuk
 */
public class InsertarParte extends javax.swing.JFrame {

    /**
     * Creates new form InsertarParte
     */
    JFrame principal;
    
    public WindowListener c = new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent e) {
            cerrar(principal);
        }
    };
    
    public InsertarParte(JFrame p) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.addWindowListener(c);
        this.setVisible(true);
        principal = p;
    }
    
    void cerrar(JFrame p){
        p.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panelinsertar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        FabricanteCombo = new javax.swing.JComboBox();
        FabricanteLabel = new javax.swing.JLabel();
        MarcaLabel = new javax.swing.JLabel();
        NombreField = new javax.swing.JTextField();
        NombreLabel = new javax.swing.JLabel();
        MarcaField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panelinsertar.setBackground(new java.awt.Color(51, 51, 51));
        Panelinsertar.setForeground(new java.awt.Color(51, 51, 51));
        Panelinsertar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Panelinsertar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 73, -1, -1));

        FabricanteCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Panelinsertar.add(FabricanteCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        FabricanteLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        FabricanteLabel.setText("Fabricante");
        Panelinsertar.add(FabricanteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 29, -1, -1));

        MarcaLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        MarcaLabel.setText("Marca");
        Panelinsertar.add(MarcaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 95, -1, -1));

        NombreField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Panelinsertar.add(NombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 151, 163, -1));

        NombreLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        NombreLabel.setText("Nombre");
        Panelinsertar.add(NombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 151, -1, -1));

        MarcaField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Panelinsertar.add(MarcaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 91, 163, -1));

        getContentPane().add(Panelinsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 372));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarParte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarParte(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox FabricanteCombo;
    private javax.swing.JLabel FabricanteLabel;
    private javax.swing.JTextField MarcaField;
    private javax.swing.JLabel MarcaLabel;
    private javax.swing.JTextField NombreField;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JPanel Panelinsertar;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
