/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repuestos;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author iFreuk
 */
public class PartesCostos extends javax.swing.JFrame {

    /**
     * Creates new form PartesCostos
     */
    JFrame principal;
    
    public WindowListener c = new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent e) {
            cerrar(principal);
        }
    };
    
    public PartesCostos(JFrame p) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.addWindowListener(c);
        cargarPartes();
        this.setVisible(true);
        principal = p;
    }
    
    void cerrar(JFrame p){
        p.setVisible(true);
        this.dispose();
    }
    
    void cargarPartes(){
        try{
            Repuestos.getPartes(ComboPartes);
            
        }catch(SQLException ex){
            Logger.getLogger(AsociarOrden.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ProveedorCombo = new javax.swing.JComboBox();
        ProveedorLabel = new javax.swing.JLabel();
        PiezaLabel = new javax.swing.JLabel();
        CostoFinal = new javax.swing.JTextField();
        PorcentajeSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        PorcentajeLabel = new javax.swing.JLabel();
        CostoLabel = new javax.swing.JLabel();
        PorcentajeField = new javax.swing.JFormattedTextField(new Integer(3));
        TITULOINSERTARp = new javax.swing.JLabel();
        PorcentajeLabel1 = new javax.swing.JLabel();
        ComboPartes = new javax.swing.JComboBox<>();
        AsociarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Costo de Parte");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProveedorCombo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ProveedorCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Auto Repuestos Jiménez", "Autopartes Mandi", "Autopartes USA", "J y A Autopartes", "LACOR Repuestos", "Megapartes Martínez", "Repuestos ABZ", "Repuestos Zúñiga", "Servicios Omega", "Super Repuestos" }));
        jPanel1.add(ProveedorCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        ProveedorLabel.setBackground(new java.awt.Color(204, 204, 204));
        ProveedorLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ProveedorLabel.setForeground(new java.awt.Color(255, 255, 255));
        ProveedorLabel.setText("Proveedor");
        jPanel1.add(ProveedorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        PiezaLabel.setBackground(new java.awt.Color(204, 204, 204));
        PiezaLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PiezaLabel.setForeground(new java.awt.Color(255, 255, 255));
        PiezaLabel.setText("Pieza");
        jPanel1.add(PiezaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        CostoFinal.setEditable(false);
        CostoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostoFinalActionPerformed(evt);
            }
        });
        jPanel1.add(CostoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 118, -1));

        PorcentajeSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PorcentajeSpinnerStateChanged(evt);
            }
        });
        jPanel1.add(PorcentajeSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 57, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 76, -1, -1));

        PorcentajeLabel.setBackground(new java.awt.Color(204, 204, 204));
        PorcentajeLabel.setForeground(new java.awt.Color(255, 255, 255));
        PorcentajeLabel.setText("Precio Final");
        jPanel1.add(PorcentajeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        CostoLabel.setBackground(new java.awt.Color(204, 204, 204));
        CostoLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CostoLabel.setForeground(new java.awt.Color(255, 255, 255));
        CostoLabel.setText("Costo en Colones");
        jPanel1.add(CostoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        PorcentajeField.setText("0");
        PorcentajeField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PorcentajeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorcentajeFieldActionPerformed(evt);
            }
        });
        PorcentajeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PorcentajeFieldKeyPressed(evt);
            }
        });
        jPanel1.add(PorcentajeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 134, -1));

        TITULOINSERTARp.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TITULOINSERTARp.setForeground(new java.awt.Color(255, 255, 255));
        TITULOINSERTARp.setText("Acutalizar costos por Parte");
        jPanel1.add(TITULOINSERTARp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        PorcentajeLabel1.setBackground(new java.awt.Color(204, 204, 204));
        PorcentajeLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PorcentajeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        PorcentajeLabel1.setText("Porcentaje Beneficio");
        jPanel1.add(PorcentajeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        ComboPartes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(ComboPartes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 180, -1));

        AsociarButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        AsociarButton.setText("Asociar ✅");
        AsociarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsociarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AsociarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 160, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CostoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostoFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostoFinalActionPerformed

    private void PorcentajeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorcentajeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PorcentajeFieldActionPerformed

    private void PorcentajeSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PorcentajeSpinnerStateChanged
      CostoFinal.setText(calcValor());
    }//GEN-LAST:event_PorcentajeSpinnerStateChanged

    private void PorcentajeFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PorcentajeFieldKeyPressed
      CostoFinal.setText(calcValor());
    }//GEN-LAST:event_PorcentajeFieldKeyPressed

    private void AsociarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsociarButtonActionPerformed
       CostoFinal.setText(calcValor());
        try {
            Repuestos.CostoCreateOrUpdate(ProveedorCombo.getSelectedItem().toString(), ComboPartes.getSelectedIndex()+1, Integer.parseInt(PorcentajeField.getText()), (int)PorcentajeSpinner.getValue());
        } catch (SQLException ex) {
            Logger.getLogger(PartesCostos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AsociarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartesCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartesCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartesCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartesCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartesCostos(null).setVisible(true);
            }
        });
    }
    
    private String calcValor(){
    float Costo = (Integer) PorcentajeField.getValue();
    float Porcentaje = (Integer) PorcentajeSpinner.getValue();
    return ""+(Costo+Costo*(Porcentaje/100)+(Costo*0.13));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AsociarButton;
    private javax.swing.JComboBox<String> ComboPartes;
    private javax.swing.JTextField CostoFinal;
    private javax.swing.JLabel CostoLabel;
    private javax.swing.JLabel PiezaLabel;
    private javax.swing.JFormattedTextField PorcentajeField;
    private javax.swing.JLabel PorcentajeLabel;
    private javax.swing.JLabel PorcentajeLabel1;
    private javax.swing.JSpinner PorcentajeSpinner;
    private javax.swing.JComboBox ProveedorCombo;
    private javax.swing.JLabel ProveedorLabel;
    private javax.swing.JLabel TITULOINSERTARp;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
