/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repuestos;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JFrame;

/**
 *
 * @author iFreuk
 */
public class PartesCostos extends javax.swing.JFrame {

    /**
     * Creates new form PartesCostos
     */
    JFrame principal;
    
    public WindowListener c = new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent e) {
            cerrar(principal);
        }
    };
    
    public PartesCostos(JFrame p) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.addWindowListener(c);
        this.setVisible(true);
        principal = p;
    }
    
    void cerrar(JFrame p){
        p.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ProveedorCombo = new javax.swing.JComboBox();
        ProveedorLabel = new javax.swing.JLabel();
        PiezaLabel = new javax.swing.JLabel();
        FabricanteLabel = new javax.swing.JLabel();
        PiezaCombo = new javax.swing.JComboBox();
        FabricanteCombo = new javax.swing.JComboBox();
        CostoFinal = new javax.swing.JTextField();
        PorcentajeSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        PorcentajeLabel = new javax.swing.JLabel();
        CostoLabel = new javax.swing.JLabel();
        PorcentajeField = new javax.swing.JFormattedTextField(new Integer(3));

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProveedorCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(ProveedorCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 32, -1, -1));

        ProveedorLabel.setBackground(new java.awt.Color(204, 204, 204));
        ProveedorLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ProveedorLabel.setText("Proveedor");
        jPanel1.add(ProveedorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 31, -1, -1));

        PiezaLabel.setBackground(new java.awt.Color(204, 204, 204));
        PiezaLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PiezaLabel.setText("Pieza");
        jPanel1.add(PiezaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 76, -1, -1));

        FabricanteLabel.setBackground(new java.awt.Color(204, 204, 204));
        FabricanteLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        FabricanteLabel.setText("Fabricante");
        jPanel1.add(FabricanteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        PiezaCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(PiezaCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 76, -1, -1));

        FabricanteCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(FabricanteCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 131, -1, -1));

        CostoFinal.setEditable(false);
        CostoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostoFinalActionPerformed(evt);
            }
        });
        jPanel1.add(CostoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 295, 118, -1));

        PorcentajeSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PorcentajeSpinnerStateChanged(evt);
            }
        });
        jPanel1.add(PorcentajeSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 214, 57, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 76, -1, -1));

        PorcentajeLabel.setBackground(new java.awt.Color(204, 204, 204));
        PorcentajeLabel.setText("Porcentaje Beneficio");
        jPanel1.add(PorcentajeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 219, -1, -1));

        CostoLabel.setBackground(new java.awt.Color(204, 204, 204));
        CostoLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CostoLabel.setText("Costo en Colones");
        jPanel1.add(CostoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 130, -1, -1));

        PorcentajeField.setText("0");
        PorcentajeField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PorcentajeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorcentajeFieldActionPerformed(evt);
            }
        });
        PorcentajeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PorcentajeFieldKeyPressed(evt);
            }
        });
        jPanel1.add(PorcentajeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 128, 134, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 372));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CostoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostoFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostoFinalActionPerformed

    private void PorcentajeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorcentajeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PorcentajeFieldActionPerformed

    private void PorcentajeSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PorcentajeSpinnerStateChanged
      CostoFinal.setText(calcValor());
    }//GEN-LAST:event_PorcentajeSpinnerStateChanged

    private void PorcentajeFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PorcentajeFieldKeyPressed
      CostoFinal.setText(calcValor());
    }//GEN-LAST:event_PorcentajeFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartesCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartesCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartesCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartesCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartesCostos(null).setVisible(true);
            }
        });
    }
    
    private String calcValor(){
    float Costo = (Integer) PorcentajeField.getValue();
    float Porcentaje = (Integer) PorcentajeSpinner.getValue();
    return ""+(Costo+Costo*(Porcentaje/100));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CostoFinal;
    private javax.swing.JLabel CostoLabel;
    private javax.swing.JComboBox FabricanteCombo;
    private javax.swing.JLabel FabricanteLabel;
    private javax.swing.JComboBox PiezaCombo;
    private javax.swing.JLabel PiezaLabel;
    private javax.swing.JFormattedTextField PorcentajeField;
    private javax.swing.JLabel PorcentajeLabel;
    private javax.swing.JSpinner PorcentajeSpinner;
    private javax.swing.JComboBox ProveedorCombo;
    private javax.swing.JLabel ProveedorLabel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
